services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile${DOCKER_ENV:+.${DOCKER_ENV}}
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    develop:
      watch:
        - action: sync
          path: ./
          target: ./rails
          ignore: [log/*, Dockerfile, docker-compose.yml, Dockerfile.dev, docker-compose-dev.yml]
        - action: rebuild
          path: Gemfile
        - action: sync+restart
          path: ./config
          target: ./rails/config
          ignore: [routes/*]
    container_name: sidekiq
    command: bundle exec sidekiq -q critical,2 -q high,1.5 -q default,1 -q low,0.5
    volumes:
      - app_logs:/rails/log
    depends_on:
      - redis
      - db
      - elasticsearch
    env_file:
      - path: .env
    healthcheck:
      test: ["CMD", "bundle", "exec", "sidekiq", "--check"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:latest
    env_file:
      - path: .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  rails:
    build:
      context: .
      dockerfile: Dockerfile${DOCKER_ENV:+.${DOCKER_ENV}}
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    container_name: rails
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
      - sidekiq
      - elasticsearch
    env_file:
      - path: .env
    volumes:
      - app_logs:/rails/log
    develop:
      watch:
        - action: sync
          path: ./
          target: ./rails
          ignore: [log/*, Dockerfile, docker-compose.yml, Dockerfile.dev, docker-compose-dev.yml]
        - action: rebuild
          path: Gemfile
        - action: sync+restart
          path: ./config
          target: ./rails/config
          ignore: [routes/*]
  

volumes:
  db_data:
  redis_data:
  app_logs:
  esdata:
